#!/usr/bin/env python3
# ============================================================================
#  gen_apps.py - regenerate apps.ini: one [env:<app>] per src/apps/<app>.cpp.
#
#  Inherited from uliano/blackpill-experiments. Each app is a .cpp with its own
#  main(); the only thing that differs per app is which main gets compiled,
#  expressed as a build_src_filter that starts from [common].base_src_filter
#  and adds that one file.
#
#  Run it after adding/removing an app:
#      python tools/gen_apps.py
#  (or the VS Code task "PIO: regen apps"), then reload the PlatformIO project
#  so the new env's Build/Upload buttons appear in the sidebar.
# ============================================================================
import glob
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APPS_DIR = os.path.join(ROOT, "src", "apps")
OUT = os.path.join(ROOT, "apps.ini")

apps = sorted(
    os.path.splitext(os.path.basename(p))[0]
    for p in glob.glob(os.path.join(APPS_DIR, "*.cpp"))
)

lines = [
    "; ==========================================================================",
    "; AUTO-GENERATED by tools/gen_apps.py - DO NOT EDIT BY HAND.",
    "; One [env:<app>] per src/apps/<app>.cpp (the PlatformIO 'APP switch').",
    "; Re-run the generator after adding/removing an app, then reload the project.",
    "; ==========================================================================",
    "",
]
for app in apps:
    lines += [
        "[env:%s]" % app,
        "build_src_filter = ${common.base_src_filter} +<src/apps/%s.cpp>" % app,
        "",
    ]

with open(OUT, "w", newline="\n", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("gen_apps: wrote %s with %d app(s): %s"
      % (OUT, len(apps), ", ".join(apps) or "(none)"))
