#!/usr/bin/env python3
# ============================================================================
#  gen_apps.py - regenerate apps.ini: the env matrix over src/apps/<app>.cpp.
#
#  Inherited from uliano/blackpill-experiments. Each app is a .cpp with its own
#  main(); the only thing that differs per app is which main gets compiled,
#  expressed as a build_src_filter that starts from [common].base_src_filter
#  and adds that one file.
#
#  Per app, on the default board (AVR128DB48, the [env] board):
#    [env:<app>]        release build (-Os, production firmware)
#    [env:<app>-debug]  build_type = debug -> debug_build_flags from
#                       platformio.ini (-Og -g3 -ggdb3 -fno-inline); use this
#                       one for every debug session (pio debug -e <app>-debug)
#
#  BOARD MATRIX. An env is a BUILD (app x board TYPE), never a physical board:
#  which chip on which desk is the bench manifest's job (tools/bench_boards.py)
#  and the orchestrator's (tools/bench.py). An app that is meant to build for
#  more than the bench chip says so in its header comment:
#
#      // pio: boards = db28,db32,db48
#
#  and then also gets, per extra board type:
#    [env:<app>-db28]        release for board AVR128DB28
#    [env:<app>-db28-debug]  its debug twin
#
#  db48 is the default and always present as the bare [env:<app>] pair, so
#  naming it in the boards line changes nothing. Env names may only contain
#  [A-Za-z0-9_-] (PlatformIO's ENVNAME_RE), hence the '-db28' suffix rather
#  than an '@db28' one. NOTE: [env] in platformio.ini pins the debug server to
#  -d avr128db48; a debug session on another board type needs that line edited.
#
#  Per-app env overrides: any other line of the form
#      // pio: monitor_speed = 115200
#  becomes an option of EVERY env of that app. Keeps app-specific facts (a
#  different console baud) next to the app.
#
#  Run it after adding/removing an app or changing a "// pio:" line:
#      python tools/gen_apps.py
#  (or the VS Code task "PIO: regen apps"), then reload the PlatformIO project
#  so the new env's Build/Upload buttons appear in the sidebar.
# ============================================================================
import glob
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APPS_DIR = os.path.join(ROOT, "src", "apps")
OUT = os.path.join(ROOT, "apps.ini")

# Board type -> PlatformIO board (boards/<board>.json). The key is the short
# name used in a "// pio: boards =" line, in the bench manifest and on the
# bench.py command line; DEFAULT_BOARD is the one [env] already selects.
BOARDS = {
    "db28": "AVR128DB28",
    "db32": "AVR128DB32",
    "db48": "AVR128DB48",
}
DEFAULT_BOARD = "db48"

PIO_LINE = re.compile(r"^//\s*pio:\s*([A-Za-z_]+)\s*=\s*(.+?)\s*$")


def env_name(app, board):
    """The env of an app on a board type: the bare name on the default board."""
    return app if board in (None, DEFAULT_BOARD) else "%s-%s" % (app, board)


def header_options(app):
    """The app's "// pio:" lines: (options for its envs, extra board types)."""
    path = os.path.join(APPS_DIR, app + ".cpp")
    opts = []
    boards = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = PIO_LINE.match(line)
            if not m:
                continue
            key, value = m.group(1), m.group(2)
            if key == "boards":
                for name in value.replace(",", " ").split():
                    if name not in BOARDS:
                        raise SystemExit(
                            "gen_apps: %s.cpp: unknown board '%s' "
                            "(known: %s)" % (app, name, ", ".join(sorted(BOARDS)))
                        )
                    if name != DEFAULT_BOARD and name not in boards:
                        boards.append(name)
            else:
                opts.append("%s = %s" % (key, value))
    return opts, boards


def emit(env, app, extra, debug=False, board=None):
    block = [
        "[env:%s]" % env,
        "build_src_filter = ${common.base_src_filter} +<src/apps/%s.cpp>" % app,
    ]
    if board is not None:
        block.append("board = %s" % BOARDS[board])
    if debug:
        block.append("build_type = debug")
    return block + extra + [""]


def main():
    apps = sorted(
        os.path.splitext(os.path.basename(p))[0]
        for p in glob.glob(os.path.join(APPS_DIR, "*.cpp"))
    )
    lines = [
        "; ==========================================================================",
        "; AUTO-GENERATED by tools/gen_apps.py - DO NOT EDIT BY HAND.",
        "; Envs per src/apps/<app>.cpp (the PlatformIO 'APP switch'):",
        ";   [env:<app>]        release (-Os)      -> production uploads",
        ";   [env:<app>-debug]  debug (-Og -g3...) -> pio debug -e <app>-debug",
        "; An app carrying a '// pio: boards = db28,...' line also gets one such",
        "; pair per extra board type, named [env:<app>-db28] (build = app x board",
        "; TYPE; which physical board is tools/bench_boards.py's business).",
        "; Re-run the generator after adding/removing an app, then reload the project.",
        "; ==========================================================================",
        "",
    ]
    total_envs = 0
    for app in apps:
        extra, boards = header_options(app)
        for board in [None] + boards:
            env = env_name(app, board)
            lines += emit(env, app, extra, board=board)
            lines += emit(env + "-debug", app, extra, debug=True, board=board)
            total_envs += 2

    with open(OUT, "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("gen_apps: wrote %s with %d env(s) for %d app(s): %s"
          % (OUT, total_envs, len(apps), ", ".join(apps) or "(none)"))


if __name__ == "__main__":
    main()
