#!/usr/bin/env python3
# ============================================================================
#  gen_apps.py - regenerate apps.ini: two envs per src/apps/<app>.cpp.
#
#  Inherited from uliano/blackpill-experiments. Each app is a .cpp with its own
#  main(); the only thing that differs per app is which main gets compiled,
#  expressed as a build_src_filter that starts from [common].base_src_filter
#  and adds that one file.
#
#  Per app:
#    [env:<app>]        release build (-Os, production firmware)
#    [env:<app>-debug]  build_type = debug -> debug_build_flags from
#                       platformio.ini (-Og -g3 -ggdb3 -fno-inline); use this
#                       one for every debug session (pio debug -e <app>-debug)
#
#  Run it after adding/removing an app:
#      python tools/gen_apps.py
#  (or the VS Code task "PIO: regen apps"), then reload the PlatformIO project
#  so the new env's Build/Upload buttons appear in the sidebar.
# ============================================================================
import glob
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APPS_DIR = os.path.join(ROOT, "src", "apps")
OUT = os.path.join(ROOT, "apps.ini")

apps = sorted(
    os.path.splitext(os.path.basename(p))[0]
    for p in glob.glob(os.path.join(APPS_DIR, "*.cpp"))
)

lines = [
    "; ==========================================================================",
    "; AUTO-GENERATED by tools/gen_apps.py - DO NOT EDIT BY HAND.",
    "; Two envs per src/apps/<app>.cpp (the PlatformIO 'APP switch'):",
    ";   [env:<app>]        release (-Os)      -> production uploads",
    ";   [env:<app>-debug]  debug (-Og -g3...) -> pio debug -e <app>-debug",
    "; Re-run the generator after adding/removing an app, then reload the project.",
    "; ==========================================================================",
    "",
]
# Per-app env overrides: an app may carry lines like
#     // pio: monitor_speed = 115200
# in its header comment; each becomes an option of BOTH its envs. Keeps
# app-specific facts (a different console baud) next to the app.
import re
PIO_LINE = re.compile(r"^//\s*pio:\s*([A-Za-z_]+)\s*=\s*(.+?)\s*$")

def overrides(app):
    path = os.path.join(APPS_DIR, app + ".cpp")
    out = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = PIO_LINE.match(line)
            if m:
                out.append("%s = %s" % (m.group(1), m.group(2)))
    return out

for app in apps:
    extra = overrides(app)
    lines += [
        "[env:%s]" % app,
        "build_src_filter = ${common.base_src_filter} +<src/apps/%s.cpp>" % app,
    ] + extra + [
        "",
        "[env:%s-debug]" % app,
        "build_src_filter = ${common.base_src_filter} +<src/apps/%s.cpp>" % app,
        "build_type = debug",
    ] + extra + [
        "",
    ]

with open(OUT, "w", newline="\n", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("gen_apps: wrote %s with %d app(s): %s"
      % (OUT, len(apps), ", ".join(apps) or "(none)"))
